quantizer_kwargs:
  d: 4
  n_bits: 2
  cluster_ignore_norms: True
  n_iters: 100
  norm_order: 
    - 0
    - 1
  zero:
  - False
  - False
  initialize_method: 'kmeans'
alignment_kwargs:
  clip_grad: 0.1
  discrete_update_every: 10000
  low_bound: 1.0e-05
  lr: 0.001
  lr_multiplier: 1
  n_iters: 100
  patience: 1000
  patience_scheduler: 1000
  verbose: 10
  reinitailize_optimizer: False
  eps: 1.0e-05
seed: 0
# quantizer_type: '1st_order'
# hessian_regularization: 0.1
