alignment_kwargs:
  clip_grad: 0.1
  discrete_update_every: 100
  low_bound: 1.0e-05
  lr: 0.001
  lr_multiplier: 0.333333
  n_iters: 1000
  patience: 500
  patience_scheduler: 10
  verbose: 10
hessian_regularization: 0.1
quantizer_kwargs:
  cluster_ignore_norms: true
  d: 5
  initialize_method: kmeans
  n_bits: 2
  n_iters: 10
  norm_order:
  - 0
  - 1
  zero:
  - false
  - false
quantizer_type: 1st_order
seed: 0
