alignment_kwargs:
  clip_grad: 0.1
  discrete_update_every: 10000
  eps: 0.001
  low_bound: 1.0e-05
  lr: 0.001
  lr_multiplier: 0.333333
  n_iters: 100
  patience: 100
  patience_scheduler: 1000
  reinitailize_optimizer: false
  verbose: 1
quantizer_kwargs:
  cluster_ignore_norms: true
  d: 4
  initialize_method: kmeans
  n_bits: 2
  n_iters: 100
  norm_order:
  - 0
  - 1
  zero:
  - false
  - false
quantizer_type: 1st_order
seed: 0
