defaults:
  # compression config
  - compress: vq
  - eval: default

base_model: meta-llama/Llama-2-7b-hf
seqlen: -1 # -1 means native seqlen
verbose: True
#paths to the various files
weight_path: ./models/${base_model}/original_weights
hessianDiag_path: ./models/${base_model}/hessianDiags/seed_0/pajama/128
save_path: ./models/${base_model}/compressed/test_compress
temp_path: ./models/${base_model}/temp/test_compress

seed: 0
add_bias: False