method: "Permute"

kwargs:
  permutation_config:
    N: 2
    M: 4
    n_permutations0: 4
    n_permutations1: 4
    mask_init: 1 
    low_rank: 4

  loss_fn_config:
    name: "l2"
    wrt_to_normalized: False
    trainable_normalizer: True
    loss_weighting: None
    hard_frac: 0.75
    lambda_sparse: 10
    lambda_binary: 10


  optimizer_config:
    _target_: "torch.optim.Adam"
    lr: 1e-3

  beta_scheduler_config:
    _target_: src.utils.beta_schedulers.LinearScheduler
    beta_start: 2.0
    beta_end: 1.0

  n_iters: 1000

  normalizer_kwargs:
    norm_order: []
    zero: []
    p: 2


  logging_path: "/data/lliu/NoWAG/test/permute.txt"
  plotting_path: "/data/lliu/NoWAG/test/permute.png"



