method: LinearVQ
kwargs:
  d: 6
  ignore_norms: true
  n_bits: 2
  n_inits: 1
  n_iters: 100
  initialize_method: kmeans++
  initialize_kwargs:
    deterministic: False
    multiple_each_time: 1.0
  normalizer_kwargs:
    norm_order:
    - 0
    - 1
    zero:
    - false
    - false
    p: 2